### ISSUE TITLE
Some functions swallows error

### ISSUE THREAD

**Issue by unlight** [ludohenin/gulp-inline-ng2-template#68] opened 2016-09-30 20:16 UTC
Which prevents catching.

See comments.
```js
  function processStyles(done) {
    if (opts.styleProcessor) {
      CSS = true;
      extend(opts, cssOptions());
      execute(function () { // First argument is error, it should be forwarded to done()
        reset();
        done(null);
      });
    }
  }
```
Same in other functions:
https://github.com/ludohenin/gulp-inline-ng2-template/blob/master/parser.js#L82
https://github.com/ludohenin/gulp-inline-ng2-template/blob/master/parser.js#L72

**Comment by ludohenin** [comment] 2016-10-26 17:02
this is a duplicate of #60

**Closed** 2016-10-26 17:02 UTC
Labels: duplicate
